# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('from_user', models.CharField(default=None, max_length=255)),
                ('notes', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
