# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notes_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
    ]
