# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-10 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180810_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(default='提交简历', max_length=20),
        ),
    ]
