# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='position_level',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
