# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-13 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_notes_position_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_level', models.CharField(default=None, max_length=255)),
                ('base_num', models.IntegerField(default=0, verbose_name='基数')),
            ],
        ),
    ]
