# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-13 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_base_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='base_num',
            field=models.IntegerField(default=0, verbose_name='基数'),
        ),
    ]
