# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notes_base_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_from_user',
            name='gold_bean',
            field=models.FloatField(default=0, verbose_name='金豆数'),
        ),
    ]
